# -*- coding: utf-8 -*-
"""
Created on Sat Nov 27 12:20:11 2021

@author: Design Group 3
"""
from SLiCAP import *

makeNetlist('emptyCircuit.asc', 'Design Overview')
i1 = instruction()
i1.setCircuit('emptyCircuit.cir')

head2html('Active antenna')
img2html('activeAntennaAssignment.svg', 800)
text2html('An active whip antenna is located far from its connected radio receiver. The signal from the antenna is too weak for the receiver, therefore, an amplifier is necessary. The amplifier will be based on CMOS180 technology and will consist of MOSFETS. There are some requirements given for the amplifier so the antenna can be amplified properly.')
head2html('Design requirements')

text2html("The input impedance of the receiver equals $50 \Omega$. A $50 \Omega$ coax cable with SMA connectors at both ends, will be used to connect the active antenna with the receiver.")
text2html("The active antenne is intended to be used for the reception of radio signals in outdoor environments. The operating temperature of the active antenna should range from $-25 ^{\circ} C$ to $+70 ^{\circ} C$.")
          
text2html("The power supply for the antenna will be located nearby the receiver. The power consumtion of the antenna should be less than 0.25W. A small interface box is used to combine the supply power and the signal in such a way that both the signal and the supply power can be transported over the $50\Omega$ coax cable, while zero DC bias voltage is maintained at the input of the receiver. This interface box is located at a short distance of the receiver.")

text2html("The $-3dB$ frequency range of the active antenna should equal $10kHz$ to $30MHz$. The $1dB$ compression level at the output of the amplifier, measured at the input of the receiver should be above $+0dBm$ ($0dBm =1mW$ in $50\Omega$). At the antenna input, this should be equivalent with an electrical field strength of $0.45Vm$.")          
          
text2html("The active antenna to be designed has requirements for noise input levels. For different frequencies, there are limits for the antenna-referred equivalent noise.")

text2html("The antenna can be represented by an ideal voltage source in series with a capacitor. The voltage source converts the signal to a voltage")
text2html("The antenna is specified to be a maximum of $0.5m$ long. From the model, the gain from E-field to voltage can be determined:")
text2html("From the model: $V = E \ell$, so $V = 0.5E V$")
text2html("In addition to the voltage, the capacitor is determined from the model as well")
text2html("From the model: $C = 10 * 10^{-12} \ell$, so $C = 5 pF$")


head2html("Noise requirements")

text2html("The requirements for the noise of the antenna are as follows:")
text2html("$10 kHz \implies E = 100nVm^{-1}Hz^{-½} \implies V = 50nVHz^{-½} = 2.5 * 10^{-15}V^2/Hz$ <br /> \
           $100 kHz \implies E = 10nVm^{-1}Hz^{-½} \implies V = 5nVHz^{-½} = 2.5 * 10^{-17}V^2/Hz$ <br /> \
           $1 MHz \implies E = 5nVm^{-1}Hz^{-½} \implies V = 2.5nVHz^{-½} = 6.25 * 10^{-18}V^2/Hz$ <br /> \
           $30 MHz \implies E = 5nVm^{-1}Hz^{-½} \implies V = 2.5nVHz^{-½} = 6.25 * 10^{-18}V^2/Hz$")
text2html("Like visible from these requirements, the noise floor cutoff frequency is at around $100 kHz$ and the E-field noise density limit at the noise floor is $5nVm^{-1}Hz^{-½}")
text2html("From the model, the E-field noise can be converted to a voltage, V = 0.5 x 5nVm^{-1}Hz^{-½} = 2.5nVHz^{-½}")
text2html("This floor noise voltage can be generated by a noisy resistor, since Vn = sqrt(4kTR). The value of the resistor therefore is R = sqrt(Vn/(4kT)) = 2.5n<sup>2</sup>/(4kt) = 377 &Omega;")
# text2html("When using a cascaded design for an amplifier, the first stage is most predominant for the noise. The second stage almost does not contribute to the input-referred noise. This means that the first stage should be focussed on achieving the required noise specificaitons. The circuit shown in the section 'Circuit Data' is a SLiCAP noise model for a MOSFET, which is connected to the ouput of the antenna. In the seciton Noise Level, the conclusion for the parameters to gain the required noise level is discussed")
# text2html("This means that a starting point for the input-stage transistor can be at a gm of 1/377 = 0.0027 A/V.")
#text2html("When the transistor is scale using the following parameters: ID=0.5m, W=10u, L=180n, the transistor is in moderate inversion (inversion coefficient of 14) and has a gm of 0.0030. This is a good starting point")
#text2html("Now, the noise floor is correctly determined, however, the cutoff frequency of the 1/f noise is far too high. This means that the input capacitance needs to be increased in order to bring this cutoff frequency down. By multiplying both the width and length by the same amount, the corner frequency can be shifted. However the gm will change as well due to this action. This can be compensated by varying the drain current again.")

text2html("Intermodulation products in the frequency band of interest should be below -50dBm, measured at the input of the receiver.")

text2html("The electronics for the active antenna, should be realized in CMOS18 technology and operate on a power supply of maximally 1.8V.")

text2html("The active antenna should be protected against electrostatic discharge (ESD)")